### ISSUE TITLE
Better repository organization

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2069]
We need to discuss a few things about the project. Of course we need tux3 to come back, but some issues we can discuss without him:
- [ ] ~~create roadmap~~ - better issues organization, ~~mile stones, versioning, ~~CHANGELOG.md,~~ releases
- [x] bug-fixing/add features sprints - we have >400 open issues (>half of them are duplicated or invalid!)
- [x] responsibility list - who is responsible for what, issues to related bugs should be automatically assigned to that person? [solved - assign yourself to book code review or issue]
- [x] what do we do if tux is hit by a bus?
- [x] add more admins to the repo, this is second time @tux3 is on holidays and we can't move the project forward. Suggestion: admin should never merge their own code.
- [ ] too much bikeshedding!

Since March, only we made major code changes in the repo so I want you to tell your opinion about issues above:
@TheSpiritXIII @zetok  @PKEv @tux3

**Comment by TheSpiritXIII** [comment]
For the last two points, I think that qTox should be owned by the Tox Project for extra insurance. If tux3 were to give write permissions to just one other person, then what happens when tux3 and that other person both disappear simultaneously? If the Tox Project owns it, then this would never be a possibility and I expect that they wouldn't accept pull requests, but would only be in charge of appointing a new maintainer with write permissions.

**Comment by ovalseven8** [comment]
I think it's a good idea to start such a discussion, @agilob. :+1: 

My thoughts:

> - [ ] create roadmap - better issues organization, mile stones, versioning, CHANGELOG.md, releases

**Milestones:** Don't think it is that important at the moment because qTox is still alpha software. And it is also an big effort to maintain it. In my mind, if someone would like to do it, yes. But if not, also no problem. The resources should be used for more important things.

**Versioning:** Absolute support this suggestion. So, it's possible for all users to quote the qTox version if they are creating an issue for example. 

**Changelog:** Well, when qTox is stable someday, a changelog is necessary. At the moment, I would also say: If someone would like to maintain it, great. If there is no one, also no problem.

> - [ ] bug-fixing/add features sprints - we have >400 open issues (>half of them are duplicated or invalid!)

That's an very important topic. Because of that, there should be someone who is maintaining the issues. Assign flags, close issues, reopen issues and so on. As mentioned, at the moment there are over 400 open issues. Currently, it's not really possible to keep track of all of them.

So, there should absolutely be someone who is responsible for the maintenance of the issues. And, of course, developers who are working on the issues so that we don't lose overview.

> - [ ] add more admins to the repo, this is second time @tux3 is on holidays and we can't move the project forward. Suggestion: admin should never merge their own code.

Yes, here should change something. Perhaps create a new  neutral repository, like github.com/Tox/qTox? In any case, qTox and other projects, shouldn't be depending on a single person.

Because of that, yes, there should be more admins. On the other side, it's also a very difficult topic. Everybody who has admin rights, must be **_absolutely**_ trustworthy and reliable! So, no hasty action here.

Additionally:
I agree that **_developers should not merge their own code.**_ There should be at least one other developer who reviewed the commits. Quality management is an important issue, especially for the Tox-related projects.

**Comment by suhr** [comment]
Picrelated.
![SO SLOW](https://d.maxfile.ro/anyfdvljob.jpg)

> mile stones, versioning, CHANGELOG.md, releases

qTox is fully rolling release (and so is toxcore btw), so all these things are not very helpful.

> bug-fixing/add features sprints - we have >400 open issues (>half of them are duplicated or invalid!)

At first we need priority tags.

> Suggestion: admin should never merge their own code.

Too restricting. Consider “admin can't merge non-trivial changes without someone else _review_”.

**Comment by agilob** [comment]
@TheSpiritXIII afair tux didn't want to add qtox to tox fund, not sure why so lets leave this topic. I think it would be better for qtox to be independent, but with more 'official' developers, that's why we need at least 2 more. I would suggest adding me, you and zetok as admins, we're from different backgrounds and we work on different aspects of qtox, but of course it's up to tux3.

@ovalseven8 

> That's an very important topic. Because of that, there should be someone who is maintaining the issues. 

I would be happy to do it, I browse them occasionally anyway when looking for a task.

> Too restricting. Consider “admin can't merge non-trivial changes without someone else review”.

I meant more important stuff, not translations, or tpyos in labels.

> qTox is fully rolling release (and so is toxcore btw), so all these things are not very helpful. 

What about monthly releases? Now all merged changes go directly to master branch, first they should go to development branch, be tested by a few people then the new could should be compiled on CI and repositories for mass updated.

**Comment by subliun** [comment]
I like the idea of using milestones. I find that github makes it easy to create and use milestones. Since I've been using issues as a todo-list of sorts for Antox, I use milestones to organise issues into 'now', 'soon' and 'someday' piles. I'm not sure how well this system would work for qTox, but it has been fairly effective for Antox so far.

**Comment by suhr** [comment]
> I meant more important stuff, not translations, or tpyos in labels.

The problem is that most of qTox code is written and merged by @tux3, and requirement of someone else will slow the development significantly.

> What about monthly releases?

Hm. Ok, that's reasonable.

> Now all merged changes go directly to master branch, first they should go to development branch, be tested by a few people then the new could should be compiled on CI and repositories for mass updated.

Development branch is redundant. Git have tags and master branch should _always_ compile. By the way, feature branches should have more reasonable names than “pr1953”.
See also: [gitflow considered harmful](http://endoflineblog.com/gitflow-considered-harmful).

**Comment by zetok** [comment]
> create roadmap - better issues organization, mile stones, versioning, CHANGELOG.md, releases

Well about that part - I've tried to ask tux3 to:
- better tag issues - he said that he will, he tagged a few issues (not really well, just the way it was) and.. that's it.
- versioning - I've told tux3 that the way it currently is is bad, and well.. He seemed to have ignored that.
- CHANGELOG.md - I've talked a bit about it to tux3, and from what I remember, he said that it takes time, which he doesn't have much anyway, and would prefer to spend time on actually improving qTox. In the end, since that wasn't really doable without tux3's cooperation, I went for the next best thing available, and I've been pushing for at least descriptive commit names.

> bug-fixing/add features sprints - we have >400 open issues (>half of them are duplicated or invalid!)

I've tried asking people to close duplicated issues, sometimes that worked, sometimes it didn't. It would require tux3's cooperation to actually do something, since he seems to rather prefer to have multiple duplicate issues open.

> what do we do if tux is hit by a bus?

Fork repo, that is all that could be done ATM if anything bad happened. About related stuff, a bit below ↓

> add more admins to the repo, this is second time @tux3 is on holidays and we can't move the project forward. Suggestion: admin should never merge their own code.

Um, that wouldn't be necessarily the best thing - rather than going with adding people to repo, an org could be used - first though tux3's cooperation for that would be needed, since he would need to move repo under qTox/ org, and then add people to it.

That's a bit unlikely, since tux3 expressed view that he can't really give write access to anyone, since he doesn't have anyone he could trust…

# 

@TheSpiritXIII

> For the last two points, I think that qTox should be owned by the Tox Project for extra insurance.

No. There are good reasons to stay clear from Tox Project, at least when it comes to stuff like write access.

Guess why toxcore repo is not under Tox/ org, but instead it's under irungentoo/ ..

With that being said, this is with how situation is right now. It may change in the future, so…

# 

Also @antis81 expressed his interest in helping qTox.
Related issue: https://github.com/antis81/qTox/issues/1

**Comment by antis81** [comment]
Yes, I'm still interested in helping the qTox project and I had short conversation recently with @tux3 via mail with pretty positive feedback. Currently I'm the second member to qTox org, but with public readonly access so far. So I cannot do anything about it now and waiting just like anybody else.

However, what I can do in the meantime, is preparing code reviews and discuss the PR's. This mostly avoids regression and helps each other to improve and understand the concepts.

When tux3 returns, we'll discuss the further steps. It makes absolutely no sense doing it now.

Apart from that, we all can go on creating PR's. It will just take some time, until everything gets merged.

**Comment by sudden6** [comment]
I'm also interested in helping qTox going forward, here are my thoughts about a few points:

**CHANGELOG** I think at the current stage of the project this is unnecessary and just creates additional work and most information is already available in the commit messages.

**versioning** I think there should be a "stable" branch, which is only synced to the master branch once every month and just receives bugfixes, but maintains a stable UI. On the other side, the auto update mechanism is pretty good to get changes tested pretty quick. Maybe different update channels like firefox?

**bug-fixing** Personaly I think there should be atleast one, better two people (redundancy ftw) providing first level support in the issues section. They should label bugs, provide people with the steps to get good logs/backtraces, assign issues to the developer they belong, check for duplicate bugs, close stale issues...
This would remove a lot of work from the main developer(s) and doesn't require very deep programming skills.

I don't know if github allows to give only write access to the issues section, but if it does I would be happy to help in this area.

**Comment by agilob** [comment]
> bug-fixing Personaly I think there should be atleast one, better two people (redundancy ftw) providing first level support in the issues section. They should label bugs, provide people with the steps to get good logs/backtraces, assign issues to the developer they belong, check for duplicate bugs, close stale issues...

That's not even possible now. It's much faster to fix problem in code I wrote then to look for bugs and problems in someones code.

**Comment by zetok** [comment]
> I don't know if github allows to give only write access to the issues section, but if it does I would be happy to help in this area.

It doesn't. At least not through its interface - there should be a way though to grant access to only issues & stuff, without access to code through its API.

**Comment by antis81** [comment]
> > I don't know if github allows to give only write access to the issues section, but if it does I would be happy to help in this area.
> 
> It doesn't. At least not through its interface - there should be a way though to grant access to only issues & stuff, without access to code through its API.

Not exactly sure, but members with read access to the repo should be able to create labels and close issues. Otherwise, why should they become a member at all? The repo itself is public, so anyone can clone and fork by it's nature.

**Comment by sudden6** [comment]
@agilob I didn't mean they should directly fix the bug, just help the user get the right information in their bugreport and relay them to the developer.

**Comment by pollend** [comment]
you could try waffle.io. It a kanban board which might be a bit easier to organize.

**Comment by agilob** [comment]
I'm totally against using another 3rd party app. Milestones and labels should be enough.

**Comment by antis81** [comment]
Reciting my own comment:

> Not exactly sure, but members with read access to the repo should be able to create labels and close issues. Otherwise, why should they become a member at all? The repo itself is public, so anyone can clone and fork by it's nature.

@zetok @sudden6 I reread the Github organisation docs and there's currently no extra write permission for issues. If you like, have a look into the Github help section [here](https://help.github.com/articles/permission-levels-for-an-organization-repository/).

However, issue only permissions don't make much sense either, as any Github member (org. member or not) can:
1. ... create a new issue
2. ... comment on issues

Only the following actions need **write** permission to the org.:
1. Close/Reopen an issue
2. Create/Delete/Assign labels
3. Edit someone else's comment.

The read permission is very similar to "any Github member" -> the repo itself is public and anybody can look into the code.

There's absolutely no problem with granting write permissions to the repo, to be able to close issues and create labels. Hope @tux3 is going to give it to someone soon, after transferring the main repo to the org. There's no way around this.

**Comment by agilob** [comment]
gitlab is so much better...

**Comment by pollend** [comment]
I thought you were against third party?

**Comment by agilob** [comment]
I just prefer gitlab over github, it's much better for opensource projects with more than one contributor.

**Comment by pollend** [comment]
maintaining your own gitlab repository is not that simple. Might be better now, but I remember having to constantly restart the sidekiq service because it crashes. In hindsight I could of used something like Supervisor to fix this. No one is stopping you from spinning up your own server and running a fork of this repository if your so inclined. Might just be better to just maintain a bug tracker rather then the repository itself. bugzilla is not too bad.

I think you can apply for an open source licence for jira.

**Comment by tux3** [comment]
Hi everyone. 

I'm slowly coming back and playing catchup, but I'm still having a bit of trouble finding the time.
I'm probably not going to be back to full speed before some time, so clearly I need to delegate some permissions, so the project won't stay stuck everytime I'm away.

Starting from today I'm granting write access with Collaborator status to @agilob, @TheSpiritXIII, @zetok and @antis81 as an attempt to give some active involved people the tools to move things forward. 
Of course I'll be watching the history pretty closely to make sure that all is going well (and that nobody is backdooring qTox!).

Thanks to everyone for helping Tox. I hope to be back to participating more actively Soon™ (and I'll try to not get hit by a bus, I promise).

**Comment by suhr** [comment]
@tux3 Great. Now _please_ merge https://github.com/tux3/qTox/pull/2035.

**Comment by agilob** [comment]
>and I'll try to not get hit by a bus, I promise

I will f' kill you.

**Comment by suhr** [comment]
Add tag “Meta” to this issue.

**Comment by agilob** [comment]
You just cauch me when I was packing my bag. I'll be back on Monday!

**Comment by sudden6** [comment]
great to see qTox going forward again!

**Comment by suhr** [comment]
Consider spiting “l-bug“ to “l-bug”, “l-crash”, “l-perf-slow” and “l-perf-bloat”.

**Comment by zetok** [comment]
@suhr I've added `I-crash` and `I-perf-slow` - what `bloat` stands for in `I-perf-bloat` ?

**Comment by suhr** [comment]
> what bloat stands for in I-perf-bloat

Too high memory usage.

**Comment by zetok** [comment]
@suhr, I've added `I-perf-memory`

---

RE: changelog - it looks like there's an open issue for it: https://github.com/tux3/qTox/issues/590

**Comment by zetok** [comment]
@antis81 could you gpg-sign your commits/merges?

Relevant part of talk on `#tox-dev`, 08-20:

```
[21:30:19] <zetok> tux3: are you pushing stuff to repo now, or can I merge ~now (30 min I guess?) PRs for e.g. translations?
[21:33:08] <tux3> zetok, I'm not currently pushing anything
[21:33:18] <zetok> ok
[21:34:01] <tux3> Just make sure to always keep HEAD signed with a good GPG key
```

**Comment by antis81** [comment]
@zetok Added to my config `git config --global user.signingkey FF9BE04C`. How to do on Github?

**Comment by zetok** [comment]
@antis81 github doesn't support signing commits, also to sign commits via cli you'll need to add `-S` to git commands

**Comment by antis81** [comment]
@zetok I also set `cd /path/to/qtox && git config --local commit.gpgsign true`, thus all my local qTox commits will be signed from now on.

**Comment by zetok** [comment]
@antis81 that's a nice config option - thanks, I also added it. On a side note, I wonder how much time will have to pass until it will interfere with `git rebase` `:P`

# 

@agilob @antis81 @TheSpiritXIII 

BTW, if you're going to / working on some issue, could you self-assign yourself to it?

I think that's the case with #800?

EDIT: btw, same should go for PRs - if you're going to review and merge it, please assign self to it.

# 

Now, since things can move on, there is a change that I would like to propose.

> versioning

People (users) are already confused with version `1.x.x` - how about switching to something like semver?
I.e. until qTox will get into stable, it should be `0.a.b`, with `a` being incremented upon bigger changes (like any of PRs from @TheSpiritXIII - if PRs like that are merged "at once", version increases by `1`, and if they're merged separately (as in, more than a few days in between), then version should be increased accordingly.

`b` would be incremented on a (bi-)weekly basis, containing usual improvements to qTox.

First, there should be a switch `v1.1` → `v0.1.1`.

Since tags `v1.*` are already being used, First stable release should start with `v2.0.0`.

**Comment by suhr** [comment]
> Since tags v1.\* are already being used

Can't we just change them?

**Comment by zetok** [comment]
they _can_ be changed..

Is this the preferred way to go about things?

**Comment by suhr** [comment]
I think so. But we should release a new version first.

**Comment by zetok** [comment]
So.. anyone against or in favour of version changes?

@agilob , @antis81 , @TheSpiritXIII , @tux3 ?

---

Aside from that, who should sign tags of new versions? Someone who will be merging changes?

# 

Also, I think that there are needed tags for audio & video things in qTox, but I'm not quite sure how they should be named.. Ideas?

**Comment by antis81** [comment]
> So.. anyone against or in favour of version changes?
1. Version should never count backwards. Next goal should be a stable `1.1`. `1.0` is already released, so `0.1` would only be more confusing. And what comes after `0.9` -> a version `2.0`?
2. I prefer the `beta` or `rc` (release candidate) suffix strategy (e.g. `1.1-beta`, `1.1-rc1`)

> Aside from that, who should sign tags of new versions? Someone who will be merging changes?

Yes. Just like a merge is signed by the one who merged.

> Also, I think that there are needed tags for audio & video things in qTox, but I'm not quite sure how they should be named.. Ideas?

Why? This would only make things more complicate. A version should clearly state, what is involved - otherwise it's of no use. A common way to do this is by adding a changelog, which is made of issue descriptions/pr's. Thus, an issue would need to be assigned to a version (milestone?).

**Comment by zetok** [comment]
> > Also, I think that there are needed tags for audio & video things in qTox, but I'm not quite sure how they should be named.. Ideas?
> 
> Why? This would only make things more complicate. A version should clearly state, what is involved - otherwise it's of no use. A common way to do this is by adding a changelog, which is made of issue descriptions/pr's. Thus, an issue would need to be assigned to a version (milestone?).

Uh, sorry for confusion I've caused - by "tags" I meant labels on qTox issues, and that's unrelated to tagging qTox versions. (I probably should have made a separate comment for it)

**Comment by antis81** [comment]
@zetok Ok no problem. :smile: Think it doesn't hurt, if you simply create the required labels then.

**Comment by agilob** [comment]
> So.. anyone against or in favour of version changes?

I vote for, but first let's merge PR from @TheSpiritXIII and update qtox to work with latest api from toxcore. First we should clean up the mess we already have.

**Comment by zetok** [comment]
> Version should never count backwards.

It's not counting backwards - just changing version system to the one that doesn't cause confusion.

> Next goal should be a stable `1.1`. `1.0` is already released, so `0.1` would only be more confusing. 

As it is now, people are _already_ confused by current versions - it's already bad, and keeping it like that will make things only worse.

> And what comes after `0.9` -> a version `2.0`?

As I've written, it could be like that, although tags also could be changed, to have "again" version `1.0` and so on.

The way I see it, there might be some minor confusion initially (short term), but in long term it should be far more beneficial.

**Comment by agilob** [comment]
> tags also could be changed, to have "again" version 1.0 and so on.

I think you meant milestones.

**Comment by zetok** [comment]
> > tags also could be changed, to have "again" version 1.0 and so on.
> 
> I think you meant milestones.

No, I meant tags, as in, git tags.

**Comment by agilob** [comment]
oki, I was thinking about github features.

**Comment by ghost** [comment]
"Better issues organization", "releases" and "too much bikeshedding!", the last open items in the list, are solved. Issue closable?
