### ISSUE TITLE
Rethink our Issue tracker

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5234]
Tasks:

- go over old issues and review if they still happen
- we currently have many labels, can we simplify them or find a better system?
- create a bug triaging system

**Comment by tox-user** [comment]
We could use a better way of accepting feature requests.

**Comment by sudden6** [comment]
yeah, and also find a way to organize them.

example points that could affect priority:

- does it fit the focus of qTox?
- how much work is it to implement the feature
- how many users want the feature?

**Comment by zetok** [comment]
Regardless of whether feature requests or bug reports, it should be stressed that each issue should contain only a single feature / bug report, since clobbering them together into a single issue makes it later on hard to evaluate whether issue has been fully addressed or not, which results in those kinds of issues being kept around "just in case", or because there's one little thing remaining left to be done from a long list of things, and that one little thing prevented issue from being closed for years.

And if even after pointing it out everywhere (CONTRIBUTING.md, issue template, wiki page for writing bug reports) user still creates an issue with many things in it, it should be mercilessly split into separate issues, with original one being only linked to and closed since it wouldn't be useful after the split.

Just like this issue should have been a meta-issue tracking 3 other task issues

- [ ] go over old issues and review if they still happen
- [ ] find a way to better manage or simplify issue tag system
- [ ] create a bug triaging system

More tasks issues could be added to the tracking list as needed.

**Comment by zetok** [comment]
- [ ]  #5365 - hiding off-topic/other posts

**Comment by jessica181920** [comment]
> * go over old issues and review if they still happen

I'm going through old issues that are pretty easy to verify if they're still relevant/applicable and commenting on the ones which I believe can be closed. There are some feature requests that in my opinion are very obviously outside of the scope/vision of qtox and toxcore (such as user profiles with photos and images on them, much like facebook) but I haven't been bothering with commenting on these.

**Comment by sudden6** [comment]
@jessica181920 that sounds great :+1:

**Comment by sudden6** [comment]
Labels have been cleaned up and some very old issues were closed. #5780 is the first step for a better bug triaging system.
